[package]
name = "anomrank"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>", "Bogdan Nițică <bogdan.nitica99@gmail.com>"]
edition = "2018"

[lib]
name = "anomrank_rs"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
